module.exports = {
    content: [
        "./src/**/*.{js,jsx,ts,tsx}",
    ],
    theme: {
        extend: {
            backgroundImage: {
                'logo': "url('/src/pictures/mucha.jpg')",
                'background': "url('/src/pictures/las.jpg')",
                'lvl1': "url('/src/pictures/slimak.jpg')",
                'lvl2': "url('/src/pictures/zolw.jpg')",
                'lvl3': "url('/src/pictures/leniwiec.jpg')",
                'lvl4': "url('/src/pictures/koala.jpg')",
                'lvl5': "url('/src/pictures/loris.jpg')",
                'lvl6': "url('/src/pictures/krowa.jpg')",
                'lvl7': "url('/src/pictures/owca.jpg')",
                'lvl8': "url('/src/pictures/kura.jpg')",
                'lvl9': "url('/src/pictures/osa.jpg')",
                'lvl10': "url('/src/pictures/piggy.jpg')",
                'lvl11': "url('/src/pictures/wiewior.JPG')",
                'lvl12': "url('/src/pictures/pies.jpg')",
                'lvl13': "url('/src/pictures/kot.jpg')",
                'lvl14': "url('/src/pictures/krolik.jpg')",
                'lvl15': "url('/src/pictures/szympans.jpg')",
                'lvl16': "url('/src/pictures/goryl.jpg')",
                'lvl17': "url('/src/pictures/hippopotam.jpg')",
                'lvl18': "url('/src/pictures/słon.jpg')",
                'lvl19': "url('/src/pictures/żyrafa.jpg')",
                'lvl20': "url('/src/pictures/dzik.jpg')",
                'lvl21': "url('/src/pictures/komar.jpg')",
                'lvl22': "url('/src/pictures/lew.jpg')",
                'lvl23': "url('/src/pictures/tygrys.jpg')",
                'lvl24': "url('/src/pictures/sarna.jpg')",
                'lvl25': "url('/src/pictures/jelen.jpg')",
                'lvl26': "url('/src/pictures/antylopa.jpg')",
                'lvl27': "url('/src/pictures/gepard.jpg')",
                'lvl28': "url('/src/pictures/orzel.jpg')",
                'lvl29': "url('/src/pictures/jastrzab.jpg')",
                'lvl30': "url('/src/pictures/mucha.jpg')",
            }
        },
    },
    plugins: [],
}